---
title: "Peter Mac Internal Nextflow Workshops"
---

These workshops are designed to provide participants with a foundational understanding of Nextflow and nf-core pipelines. Participants are expected to have prior experience with the command-line interface and working with cluster systems like Slurm. The primary goal of the workshop is to equip researchers with the skills needed to use nextflow and nf-core pipelines for their research data. 

### Course Developers & Maintainers

- Richard Lupat, Bioinformatics Core Facility
- Miriam Yeung, Cancer Genomics Translational Research Centre
- Song Li, Bioinformatics Core Facility
- Sanduni Rajapaksa, Research Computing Facility

### Current and Future Workshop Sessions

| Lesson     | Overview | Date | 
|------------|----------| ---------- |
| [Creating a workflow](./sessions/2_nf_dev_intro.html)| Introduction to developing bioinformatics workflow with Nextflow (Part1) | 29th May 2024 | 
| To-be-added | Introduction to developing bioinformatics workflow with Nextflow (Part2) | 5th Jun 2024 | 
| To-be-added | Introduction to developing bioinformatics workflow with Nextflow (Part3) | 12th Jun 2024 | 
| To-be-added | Introduction to developing bioinformatics workflow with Nextflow (Part4) | 19th Jun 2024 | 

### Past Workshop Sessions

| Session     | Overview | Date | 
|------------|----------| ---------- |
| [Introduction to Nextflow and running nf-core workflows](./sessions/1_intro_run_nf.html)| Introduction to Nextflow: Introduce nextflow’s core features and concepts + nf-core + how to run it at PeterMac | 22nd Nov 2023 | 
| [Introduction to Nextflow and running nf-core workflows](./sessions/1_intro_run_nf.html)| (Re-run) Introduction to Nextflow: Introduce nextflow’s core features and concepts + nf-core + how to run it at PeterMac | 15th May 2024 | 


### Credits and acknowledgement

^*This workshop is adapted from [Customising Nf-Core Workshop](https://sydney-informatics-hub.github.io/customising-nfcore-workshop) materials from Sydney Informatics Hub*^